apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argo-cd
spec:
  project: spof-cluster
  source:
    - repoURL: 'https://github.com/SP0Fs/mongodb-k8s.git'
      targetRevision: HEAD
      path: resources
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true