apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express
  namespace: mongodb
  labels:
    app: mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-express
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
        - name: mongodb-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-root-user
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-root-user
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongodb.mongodb.svc.cluster.local"